### ISSUE TITLE
Equipment profileNamespace variable holding presets should have diferent name

### ISSUE THREAD

**Issue by kavinsky** [11thmeu/addons#15]
- Prevent the deleting of  v1 presets.

**Comment by Thraxs** [comment]
Why have a different name?, if it's the same name then all the profiles will be kept. The data structure for now is the same so they should be compatible.

```
_loadout = profileNamespace getVariable format["meu_equipment_%1",_selected];
```

**Comment by kavinsky** [comment]
just development porpouses, will recover the original name on release.

keep this open for reminder to revert.

**Comment by Thraxs** [comment]
Changed from "meu_equipment_#" to "meu_dev_equipment_#"

**Comment by kavinsky** [comment]
change this for todays release please.

**Comment by Thraxs** [comment]
Done
