### ISSUE TITLE
Equipment module

### ISSUE THREAD

**Issue by Thraxs** [11thmeu/addons#17]
Port from 11th addons 1.2.7. Will include a rework of the interface and dialog system since the old one is not very well done and has a lot of repeated code.
- [x] Module configuration
- [x] Rework user interface
- [x] Adapt functions
- [x] Localization for dialog and messages (fix stringtable)
- [x] Send loadout functionality
- [x] ~~Add goggles slot to presets~~
- [x] CfgMEUEquipment configs
- [x] Check if TFAR/ACRE are present before saving/loading radio settings

**Comment by Thraxs** [comment]
I have finished the port of all the functionalities from 1.2.7 and it should be working well. All left to do is finish the send loadout functionality, the base configs and add some small fixes here and there.

**Comment by kavinsky** [comment]
saving radios cant save Stereo/Speaker status
