### ISSUE TITLE
Error loading frequencies in equipment module

### ISSUE THREAD

**Issue by Thraxs** [11thmeu/addons#37]
Apparently sometimes the radio doesn't work correctly after loading

**Comment by kavinsky** [comment]
could be something with sync of TFAR radio mutex?
happened today rite?

**Comment by Thraxs** [comment]
yes

**Comment by kavinsky** [comment]
this happened again?

**Comment by Thraxs** [comment]
Not that i know of, but i haven't done anything to solve it
